import { CurveFitType } from './types';

export interface AppSettings {
  theme: 'dark' | 'light';
  language: 'ko' | 'en';
  numberFormat: 'decimal' | 'scientific';
  decimals: number;
  errorBarType: 'sd' | 'sem';
  curveFit: CurveFitType;
}

export function formatValue(value: number, settings: AppSettings): string {
  if (value === null || value === undefined || isNaN(value)) return '-';
  if (settings.numberFormat === 'scientific') {
    return value.toExponential(settings.decimals);
  }
  return value.toFixed(settings.decimals);
}

export const translations = {
  en: {
    title: "ELISA Insight",
    subtitle: "Automated Standard Curve & Analysis",
    tab1: "1. Standard Curve",
    tab2: "2. Group Data Input",
    tab3: "3. Analysis Results",
    settings: "Settings",
    theme: "Theme",
    light: "Light",
    dark: "Dark",
    language: "Language",
    korean: "Korean",
    english: "English",
    numberFormat: "Number Format",
    decimal: "Decimal",
    scientific: "Scientific (e)",
    decimalPlaces: "Decimal Places",
    errorBarType: "Error Bar Type",
    curveFit: "Analysis Curve Fit",
    curveLinear: "Linear (y = mx + c)",
    curveLogarithmic: "Logarithmic (y = m*ln(x) + c)",
    curveExponential: "Exponential (y = c*e^(mx))",
    curvePower: "Power (y = c*x^m)",
    curveQuadratic: "Quadratic (y = ax² + bx + c)",
    curve4pl: "4PL (y = d + (a-d) / (1 + (x/c)^b))",
    save: "Save",
    exportPDF: "Export to PDF",
    exportExcel: "Export Spreadsheet",
    standardCurveData: "Standard Curve Data",
    addRow: "Add Row",
    subtractBackground: "Subtract Background (OD at Conc=0)",
    concentration: "Concentration",
    odValue: "OD Value",
    standardCurveLine: "Standard Curve Line",
    linearRegressionFit: "Linear Regression (y = mx + c)",
    needMoreData: "Need more valid data points",
    plateAnalysisSheet: "Plate Analysis Sheet",
    renameColumns: "Rename column headers above your input data",
    addColumn: "Add Column",
    addSampleRow: "Add Group Row",
    transpose: "Transpose Rows/Cols",
    sampleName: "Group Name",
    invalidStandardCurve: "⚠️ Standard Curve is Invalid",
    invalidStandardCurveDesc: "Please provide at least two valid standard data points on the Standard Curve tab to calculate concentration accurately.",
    computedResultsGrid: "Computed Results Grid",
    noData: "No group data provided.",
    calculatedConcentration: "Calculated Concentration",
    noChartData: "No valid chart data. Please add groups.",
    measuredOD: "Measured OD",
    predictedOD: "Predicted OD",
    regressionLine: "Regression Line",
    equation: "Eq",
    meanConcentration: "Mean Concentration",
    close: "Close",
    mean: "Mean",
    sd: "SD",
    sem: "SEM",
    cv: "CV (%)",
    conc: "Conc."
  },
  ko: {
    title: "ELISA Insight",
    subtitle: "자동화된 표준 곡선 및 데이터 분석",
    tab1: "1. 스탠다드 커브",
    tab2: "2. 그룹 데이터 입력",
    tab3: "3. 분석 결과",
    settings: "설정",
    theme: "테마",
    light: "라이트 모드",
    dark: "다크 모드",
    language: "언어",
    korean: "한국어",
    english: "영어",
    numberFormat: "숫자 표기 포맷",
    decimal: "소수점 (기본)",
    scientific: "지수 표기법 (e)",
    decimalPlaces: "소수점 자릿수",
    errorBarType: "오차 막대 기준",
    curveFit: "분석 커브 (회귀 방식)",
    curveLinear: "선형 회귀 (Linear, y = mx + c)",
    curveLogarithmic: "로그 회귀 (Logarithmic, y = m*ln(x) + c)",
    curveExponential: "지수 회귀 (Exponential, y = c*e^(mx))",
    curvePower: "거듭제곱 회귀 (Power, y = c*x^m)",
    curveQuadratic: "2차 다항식 (Quadratic, y = ax² + bx + c)",
    curve4pl: "4PL 로지스틱 회귀 (y = d + (a-d) / (1 + (x/c)^b))",
    save: "저장",
    exportPDF: "PDF로 내보내기",
    exportExcel: "스프레드시트로 내보내기",
    standardCurveData: "스탠다드 커브 데이터",
    addRow: "행 추가",
    subtractBackground: "배경값 빼기 (Conc=0의 OD값)",
    concentration: "농도",
    odValue: "OD 값",
    standardCurveLine: "스탠다드 커브 그래프",
    linearRegressionFit: "선형 회귀 (Linear Regression, y = mx + c)",
    needMoreData: "유효한 데이터 포인트가 더 필요합니다",
    plateAnalysisSheet: "플레이트 분석 시트",
    renameColumns: "입력 데이터에 맞게 열 이름을 변경하세요",
    addColumn: "열 추가",
    addSampleRow: "그룹 행 추가",
    transpose: "행/열 반전 (Transpose)",
    sampleName: "그룹명",
    invalidStandardCurve: "⚠️ 스탠다드 커브가 유효하지 않습니다",
    invalidStandardCurveDesc: "농도를 정확하게 계산하려면 스탠다드 커브 탭에 최소 두 개의 유효한 표준 데이터 포인트를 입력해주세요.",
    computedResultsGrid: "계산된 결과 그리드",
    noData: "제공된 그룹 데이터가 없습니다.",
    calculatedConcentration: "계산된 농도",
    noChartData: "유효한 차트 데이터가 없습니다. 그룹을 추가해주세요.",
    measuredOD: "측정된 OD",
    predictedOD: "예측된 OD",
    regressionLine: "회귀 선",
    equation: "수식",
    meanConcentration: "평균 농도",
    close: "닫기",
    mean: "평균",
    sd: "표준편차 (SD)",
    sem: "표준오차 (SEM)",
    cv: "변동계수 (%)",
    conc: "농도"
  }
};
